# Generated by Django 3.1.5 on 2021-04-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.checkoutaddress'),
        ),
    ]
