# Generated by Django 3.1.5 on 2021-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
