# Generated by Django 3.1.7 on 2021-03-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='index_page',
        ),
    ]
