# Generated by Django 3.1.5 on 2021-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, default='He is an employee of our business', null=True)),
            ],
        ),
    ]
