# Generated by Django 3.1.5 on 2021-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210418_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='discount',
            field=models.IntegerField(default='0'),
        ),
    ]
