# Generated by Django 3.0 on 2021-04-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.CharField(choices=[('0', 'Jewellery'), ('1', 'Furniture')], default='Jewellery', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='types',
            field=models.CharField(choices=[('0', 'Jewlery'), ('1', 'Furniture')], default='Jewlery', max_length=2),
        ),
    ]
