# Generated by Django 3.0 on 2021-04-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210409_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ref_code',
            new_name='order_id',
        ),
    ]
